Add a bunch more list functions.
* head
* tail
* empty
* apply
* reverse
(added to lib/lib.ls)

* flatten
(a new built-in)

Changes to enable this:
* Lists can now be expanded, Python style.
  (let 'l (list 2 3 4) (print *l)) => 2 3 4
  However this only works if it's *<name> not
  *(callable). So you must bind the list to a name
  first.

* Fixed a bug where the varargs "*" was not defined
  in a function if you called it with just positional
  args. As in:
  ('defun 'f 'x '* (print *)) (f 1)
  Would fail. This is now fixed, "*" is always defined,
  and would be an empty list in this situation.

* Show the current call in a bunch of the error messages.
  Error: <reason> in <thing> (errors remain terrible however)

* When variable names are looked up it now looks in local
  scope *then* global scope. This means that you can use
  function names as variables. Essentially lambdas.

* Define function now returns an instance of the new function.
  This means you can bind them to a local var name, essentially
  giving you lambdas with anonymous functions.
  (let 'fn (defun ' (print "Hello")))
  The cool thing is that even if you make another anonymous
  function later it won't matter. Yes "" in global scope will
  be different, but you can't call "" anyway, you need to use
  your reference. So as long as you keep that the function remains
  the same.

(side note: the code that does the symbol lookup is horrible,
it needs a refactor/dedupe)